language: python

python:
  - "3.8"

addons:
  apt:
    packages:
      - xvfb
      - x11-utils
      - libxkbcommon-x11-0

services: xvfb

dist: xenial

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  
before_install:
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  bash ./miniconda.sh -b -p ${HOME}/miniconda;
  export PATH=${HOME}/miniconda/bin:$PATH;
  conda install --yes python="3.8" pyqt;
  pip install -r requirements.txt
  
  sudo apt-get install libxcb-xinerama0
  sudo ln -sf /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/ /usr/bin/
  
script:
  - python demo_A_GUI_full.py simulate
  - python demo_A_GUI_full.py
  - python demo_B_GUI_minimal.py
  - python demo_C_singlethread_for_comparison.py
  - python demo_D_no_GUI.py
  - python demo_E_no_GUI.py
