language: python
sudo: required

python:
  - "3.6"
  
os:
  - linux
  - osx
  
before_install:
  if [[ $TRAVIS_OS_NAME == 'linux' ]]; then
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash ./miniconda.sh -b -p ${HOME}/miniconda;
    export PATH=${HOME}/miniconda/bin:$PATH;
  fi
  if [[ $TRAVIS_OS_NAME == 'osx' ]]; then
    bash Miniconda3-latest-MacOSX-x86_64.sh
  fi
  conda install --yes python="3.6" pyqt;
  conda install --yes numpy="1.15.0";
  conda install --yes pyqtgraph="0.10.0";
  conda install --yes pyserial="3.4.0";
  conda install --yes psutil="5.4.5";

script:
  - python Arduino_PyQt_demo_with_multithreading.py
  - python Arduino_PyQt_demo_with_multithreading__minimalistic.py
  - python Arduino_PyQt_demo_without_multithreading.py
